### ISSUE TITLE
Support EC2 IAM Role SessionToken

### ISSUE THREAD

**Issue by mweagle** [concourse/semver-resource#16]
I'm using IAM Roles for EC2 security credentials. In trying to use the `S3` driver, it looks as though the [SessionToken](http://docs.aws.amazon.com/sdk-for-go/api/aws/credentials.html) must also be set.  Just using the _AccessKeyID_ and _SecretAccessKey_ values results in an error:

```
resource script '/opt/resource/check []' failed: exit status 1

stderr:
error checking for new versions: InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.
	status code: 403, request id: XXXXXXXXXXXXXXXX
```

I didn't see a way to provide the SessionToken to [NewStaticCredentials](http://docs.aws.amazon.com/sdk-for-go/api/aws/credentials/Credentials.html#NewStaticCredentials-class_method).

**Comment by vito** [comment]
Closing as per discussion on #37 (consolidating into #291)
