### ISSUE TITLE
How to define build ID in meta?

### ISSUE THREAD

**Issue by DenisIzmaylov** [concourse/semver-resource#20]
Hi and thank you for this project!
According to SemVer 2.0 we [can define build ID](http://semver.org/#spec-item-10):

> Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Build metadata SHOULD be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence. Examples: 1.0.0-alpha+001, 1.0.0+20130313144700, 1.0.0-beta+exp.sha.5114f85.

How I can do it with `semver-resource`?

**Comment by DenisIzmaylov** [comment]
Up!

**Comment by DenisIzmaylov** [comment]
It will be extra-useful when we build dev-branch on each commit.

**Comment by DenisIzmaylov** [comment]
@vito? @mariash?

**Comment by vito** [comment]
It is not deprecated, we just can't respond to everything immediately.

If I understand correctly, you're asking for the ability to do `post`-style bumps (i.e. `1.0.0+dev.1`). This is currently not supported but would be easy to add alongside `pre`.

**Comment by DenisIzmaylov** [comment]
@vito Thank you very much for answer. So I can add it as `1.0.0-pre1`, `1.0.0-pre2`, etc?

**Comment by vito** [comment]
Yes, you could use the existing `pre` functionality if that's what you want - the thing you referenced is `post` though (`+` vs. `-`).

**Comment by mscharp** [comment]
I know this has been closed for a while, but the functionality would be beneficial.  I've submitted a PR and hopefully someone can take a look soon..
