### ISSUE TITLE
Missing support for ed25519 SSH keys

### ISSUE THREAD

**Issue by brainsik** [concourse/semver-resource#24]
While [`git-resource`](https://github.com/concourse/git-resource) supports ed25519 keys, `semver-resource` does not. This was fairly confusing as I was using the same credentials for both resources, but the semver resource was failing as if I had not supplied any key at all:

```
resource script '/opt/resource/check []' failed: exit status 1

stderr:
Cloning into '/tmp/semver-git-repo'...
Warning: Permanently added 'gist.github.com,192.30.253.119' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error checking for new versions: exit status 128
```

Switching to an RSA key fixes the error.

Please add ed25519 support to this resource so it behaves like `git-resource`. Thank you!

**Comment by vito** [comment]
I don't believe we've done anything special to either support or not support ed25519 keys. The git resource and this resource even use the same image. Are you 10000% sure the key was configured correctly and there weren't any typos?

**Comment by brainsik** [comment]
Well, I'm not able to reproduce this now. Apologies for the diversion.

**Comment by vito** [comment]
no worries!

**Comment by krishicks** [comment]
I'm able to reproduce this.

I'm using a placeholder to configure the key. Presently my git resource works but the semver resource does not.

**Comment by krishicks** [comment]
I just found the issue. Chomping the final line with `|-` on a multi-line string leads to this breaking only on the semver resource, whereas the git resource works fine.

This fixed it:

```diff
    name: version
    type: semver
    source:
      branch: version
      driver: git
      file: version
-      private_key: |-
+      private_key: |
        ...
```

**Comment by krishicks** [comment]
Further, the reason for the difference is in the way the key is read and then written.

In `git-resource`, the key is read via `jq` and piped to the file, whereas in `semver-resource` the file is read and written with `ioutil.WriteFile`. `jq` adds a newline at the end, `ioutil.WriteFile` does not:

```
# jq, as used by git-resource
$ cat <(echo '{"key": "one\ntwo" }' | jq -r '.key') | od -c
0000000   o   n   e  \n   t   w   o  \n
0000010

# ioutil.WriteFile, as used by semver-resource
$ cat writefile.go 
package main

import "io/ioutil"

func main() {
	ioutil.WriteFile("/tmp/some-file", []byte("one\ntwo"), 0644)
}
$ go run writefile.go
$ cat /tmp/some-file | od -c
0000000   o   n   e  \n   t   w   o
0000007
```

**Comment by krishicks** [comment]
Just closed?

**Comment by jtarchie** [comment]
Sorry, missed your comment about `jq`. I might have issue-ing fatigue today.

**Comment by krishicks** [comment]
Oh. It's fine if you wanted to close it because it's old or something. I
was just surprised it was closed with no reason.

**Comment by taylorsilva** [comment]
Closing this issue. Appears that the omission of a newline at the end of the key is what caused git to not read the key.
