### ISSUE TITLE
Git-tag prefix

### ISSUE THREAD

**Issue by ggeorgiev** [concourse/semver-resource#27]
An optional prefix argument that allows for multiple version tracking in the same git repo.

If you have release branches, or if you track more than one project (or component) you might need to isolate one version tracker from another. This could be easily done with a tag prefix.

**Comment by jtarchie** [comment]
@ggeorgiev, there is no git tags involved with the semver resource. Please clarify what you are referring to here. Thank!

**Comment by ggeorgiev** [comment]
There was a semver pull request at the time, that was providing using tags for storing the version. It was a bit unfinished though. I forked it and created this one: https://github.com/ggeorgiev/semver-resource

But after no response for a very long time, I am no longer PR it, I just use it from my fork.
