### ISSUE TITLE
Git tag with smart tagging

### ISSUE THREAD

**Issue by ggeorgiev** [concourse/semver-resource#34]
If you have a long pipeline with a bunch of checks until you get to the point you would like to version it there might be new changes added to the git repo. When a git driver is used it is very misleading to assume that the commit that changes the file from one version to another (which is out of the concourse control) is a delimiter between versions - if you do it in the same repo - because the actual version change potentially happened several commits earlier.

With git-tag used as versioning - this issue seems even more severe because intuitively the tag is put on the exact commit.

This is a sample implementation that overcomes this issue with getting as argument the git_resource and taking the sha from it: https://github.com/ggeorgiev/semver-resource/tree/my_ci

**Comment by harnash** [comment]
Thanks.

I'm trying to get those things together. Correct me if I am wrong or I missed something.

# git resource
## Scenario with version file kept on the same branch as the source used for development
**Steps**
1. semver-resource pulls in current-version for commit#1
2. execute some tasks
3. someone (either other build or some external process out of concourse) modifies source and pushes changes to the original resource causing current branch/head to be at commit#2
4. semver-resource pushes version creating commit#3

**Problem**
1. Deployed and tested code is up to commit#1 (inclusive)
2. Version indicates that the code tested and deployed is up to commit#2 (inclusive)
3. There is risk of race condition when one process writes version simultaneously?

## Scenario with version file kept on separate (dedicated) branch
**Problem**
1. This seems to be not vulnerable except possible race condition overwriting versions by two or more processes.

# git-tag resource
Race conditions here are mostly mitigated by git keeping tags unique.
## Scenario
1. semver-resource pulls in current-version for commit#1 (at version v0.0.1)
2. execute some tasks
3. someone (either other build or some external process out of concourse) modifies source and pushes changes to the original resource causing current branch/head to be at commit#2
4. semver-resource tagging commit#2 as new version (v0.0.2)

**Problem**
1. Deployed and tested code is up to commit#1 (inclusive)
2. Version indicates that the code tested and deployed is up to commit#2 (inclusive)

I was thinking if we should get the commit SHA from git-resource which will be probably one of the most common setup and I don't think keeping tags on different repo than source has any sense.

**Comment by jtarchie** [comment]
Since we don't have the backend for git tagging, I'm going to close this issue.

**Comment by 4n70w4** [comment]
Hi! Any news? Problem with git driver too. @jtarchie

Step to reproduce:

1) I have 0.0.4 version and make change commit b13f925d403
![image](https://user-images.githubusercontent.com/38257723/105014105-12d91700-5a51-11eb-9f9f-28e2c10f78b9.png)

2) I run test and build via concourse
![image](https://user-images.githubusercontent.com/38257723/105014311-53389500-5a51-11eb-8c54-d6312ed51702.png)

3) I make another change commit 77dfb890c7a before finish test and build via concourse
![image](https://user-images.githubusercontent.com/38257723/105014398-72cfbd80-5a51-11eb-9a8f-1e239d2a4954.png)

4) concourse finish test and build, bump version to 0.0.5 and commited 4bc8d3a8055
![image](https://user-images.githubusercontent.com/38257723/105014483-8c710500-5a51-11eb-861a-452c9dfce42b.png)

I have commit 77dfb890c7a without run test and without build but having a tag above it with a new version 0.0.5.

But this is not true. 77dfb890c7a commit did not pass tests and did not get into the build. This is misleading and confusing.
