### ISSUE TITLE
Version files stored in the same git repository result in commit message confusion

### ISSUE THREAD

**Issue by davewalter** [concourse/semver-resource#41]
Hello,

Our team stores more than one version in a single repository, where each version is on the same patch version but the build numbers are being bumped frequently. We sometimes see output like this in our git log:

```
* 593fa78f - bump to 1.12.0-build.124 (10 hours ago) <git>
* 9a3cb01e - bump to 1.12.0-build.12 (11 hours ago) <git>
* 894166d4 - bump to 1.12.0-build.123 (12 hours ago) <git>
* 224c253b - bump to 1.12.0-build.11 (17 hours ago) <git>
* 4d4c4aa2 - bump to 1.12.0-build.122 (17 hours ago) <git>
```

It would be helpful if these messages were more unique, perhaps by including the path to the version file, to reduce confusion when working in the same repository.

Thanks!
Dave

**Comment by magruene** [comment]
+1. We are using a mono-repo with each module maintaining its own version file. It would be awesome if we could override the default "bump to" commit message with an optional parameter.

**Comment by pivotal-jwinters** [comment]
@davewalter hopefully https://github.com/concourse/semver-resource/pull/64 solves your issue. If not feel free to re-open.
