### ISSUE TITLE
Version number as a variable in a shell script

### ISSUE THREAD

**Issue by cornedenhollander** [concourse/semver-resource#48]
I’m using a semver resource where the version number is stored in git. Now I want to use the version number in the filename of the build file that is stored in a S3 bucket. We have the pipeline pointing to a separate task-file which points to a shell script. It is in that shell script that I want to use the version as a variable. Now in the shell file the version variable is replaced by the literal argument text [version/number] instead of with the actual version number.

How would I use the version number from the resource in this case?

**Comment by cornedenhollander** [comment]
@vito @topherbullock

**Comment by vito** [comment]
You should cat the `version` file in your script. It is not exposed as an environment variable.

**Comment by cornedenhollander** [comment]
Thanks a lot, I'll try that!
