### ISSUE TITLE
Can't run tests without providing all build args

### ISSUE THREAD

**Issue by leggomymeggos** [concourse/semver-resource#52]
The README indicates that if there are no build args, all tests but the integration tests will run. However, running `docker build -t semver-resource .` gives the following error:

```
Failure [0.000 seconds]
[BeforeSuite] BeforeSuite
/go/src/github.com/concourse/semver-resource/check/check_suite_test.go:20

  must specify $SEMVER_TESTING_ACCESS_KEY_ID
  Expected
      <string>:
  not to be empty

  /go/src/github.com/concourse/semver-resource/check/check_suite_test.go:23
```

It seems like this shouldn't happen, or at least the README should be updated to remove the command without build args.

**Comment by fenech** [comment]
I just ran into this as well. It should be possible to build without running the integration tests, right?

**Comment by StephenWithPH** [comment]
I ran into this doing unrelated work. It's ugly, but https://github.com/VulcanTechnologies/semver-resource/blob/fix-ssh-check/Dockerfile#L28 does the job.

**Comment by taylorsilva** [comment]
It appears this has been fixed. Locally running the tests with the docker build command from the README now works.
