### ISSUE TITLE
Determining which level to bump based on outside factors?

### ISSUE THREAD

**Issue by JohnAJimenez** [concourse/semver-resource#53]
Is there a way to determine the bump type based on outside factors within a single job?

For example: I want to bump the minor version when, based on our ticketing system, a new feature is what sparked the pipeline, but bump only the patch version when a bug fix is what triggered things.
I came up with a theoretical solution but it requires multiple jobs and I wanted to make sure I wasn't hacking something that someone already elegantly solved.

**Comment by vito** [comment]
Separate jobs sounds like the way to go.
