### ISSUE TITLE
[Feature Request] Allow specifying commit message in params

### ISSUE THREAD

**Issue by tanner-bruce** [concourse/semver-resource#66]
Currently you can only set the commit message in the `source`block. We ran in to a case where following what is going on in the pipeline would be simplified by being able to set the commit message in `params` on the `put` step.

**Comment by lockan** [comment]
+1 to this request. Allowing the commit_message in the params would make more semantic sense, and would also allow for pipelines where multiple version bumps on the same repo might be required with different messaging.

**Comment by vito** [comment]
FWIW, concourse/rfcs#24 completely eliminates the difference between `source` and `params` from a resource's perspective so we should get things like this for free in the future.
