### ISSUE TITLE
[Question] Combining semver with git resource

### ISSUE THREAD

**Issue by kamsz** [concourse/semver-resource#69]
Hi,

I'd like to store version in Git repository. However, I'm falling into build loop if I'm not ignoring "version" file. If I do ignore "version" file, this leads to lost commits in future jobs (as they are ignored) and I'm unable to push back to repository. Perhaps someone has an idea how to solve this?

**Comment by Yacine-A** [comment]
I'm facing the same issue, did you solve your problem ?

**Comment by taylorsilva** [comment]
Closing this issue since @jdelic provides a solution.
