### ISSUE TITLE
git driver is broken when using private_key

### ISSUE THREAD

**Issue by StephenWithPH** [concourse/semver-resource#79]
In the original code, `isPrivateKeyEncrypted` is called before Concourse writes the key if it does not yet exist. As a result, `isPrivateKeyEncrypted`always returns an err because it is invoking `ssh-keygen` on a non-existent file, and Concourse bails out. Changing the sequencing restores order to the Force.

~https://github.com/VulcanTechnologies/semver-resource/blob/fix-ssh-check/driver/git.go#L203-L221~
**edited 2020/07/16 to add the patched snippet here which was linked above**
```
func (driver *GitDriver) setUpKey() error {
	_, err := os.Stat(privateKeyPath)
	if err != nil {
		if os.IsNotExist(err) {
			err := ioutil.WriteFile(privateKeyPath, []byte(driver.PrivateKey), 0600)
			if err != nil {
				return err
			}
		} else {
			return err
		}
	}

	if isPrivateKeyEncrypted() {
		return ErrEncryptedKey
	}

	return os.Setenv("GIT_SSH_COMMAND", "ssh -o StrictHostKeyChecking=no -i "+privateKeyPath)
}
```

This bug was introduced in https://github.com/concourse/semver-resource/pull/77. Like @wjjackson7, I find the lack of unit tests disturbing.

Without those, I'm not going to turn this into a PR, but the workaround is documented for them that stumble here.

**Comment by snoopotic** [comment]
Hi,
I am getting:
![grafik](https://user-images.githubusercontent.com/1191720/66984854-dc795300-f0bb-11e9-966b-8929ed13f8c7.png)

Is this an other issue or is that related to this? I can assure the key is w/o passphrase as we use this one successfully with the git ressource :)

**Comment by crsimmons** [comment]
I'm seeing the same as @snoopotic. Even when the git resource is successfully checking the same repo in the same pipeline with the same deploy key.

I don't think its the same error as the OP was seeing though since their fix was implemented by @vito in https://github.com/concourse/semver-resource/commit/0cc81e761e13a9f78401d6c28aca1442fdfa0be5

**Comment by eruvanos** [comment]
We also investigated this issue and it looks like it is only failing when you reference (using parameter) a private key instead of using it inline.

**Comment by DanielJonesEB** [comment]
You can fix this using the following syntax:

```yaml
private_key: |
  ((my_key))
```

Meanwhile, this does not work:

```yaml
private_key:   ((my_key))
```

The problem **is not your deploy key, and it does not have a passphrase**. I haven't had the time to look at the source of this resource, but the same key works for the Git resource.

**Comment by consolibyte** [comment]
Also seeing this issue. Are there plans to fix this?

```
stderr:
error checking for new versions: private keys with passphrases are not supported
```

**Comment by taylorsilva** [comment]
[This comment](https://github.com/concourse/semver-resource/issues/24#issuecomment-272993743) explains why. tldr: a newline `\n` is needed at the end of the file. `|` adds the newline while `|-` removes the newline.

Maybe this patch would fix it? I don't have time to test this. If someone wants to take the patch, test it, and make a PR I'm sure we'd all really appreciate it! Tag me in the PR and I'll review it.

```patch
diff --git a/driver/git.go b/driver/git.go
index db9c3cf..4fb30a4 100644
--- a/driver/git.go
+++ b/driver/git.go
@@ -227,7 +227,7 @@ func (driver *GitDriver) setUpKey() error {
 	_, err := os.Stat(privateKeyPath)
 	if err != nil {
 		if os.IsNotExist(err) {
-			err := ioutil.WriteFile(privateKeyPath, []byte(driver.PrivateKey), 0600)
+			err := ioutil.WriteFile(privateKeyPath, []byte(driver.PrivateKey+"\n"), 0600)
 			if err != nil {
 				return err
 			}
```

**Comment by evanchaoli** [comment]
This bug is extremely confusing, where exact same private key works for `git` resource but `semver` resource. Why is it still not fixed?

**Comment by StephenWithPH** [comment]
I'm closing this issue. I opened it, never heard anything from the Concourse folks. Our patch (above) worked just fine for as long as we needed it. We've since moved on.

Future searchers: _goodbye, and good luck_

**Comment by jlsalmon** [comment]
For those using JSON, the following worked for me:
```
"private_key": "((my_private_key))\n"
```
