### ISSUE TITLE
Replace deprecated aws/s3 dependency

### ISSUE THREAD

**Issue by torarnv** [concourse/semver-resource#9]
The aws/s3 dep is not maintained anymore, see https://github.com/mitchellh/goamz/issues/255

We should use this instead

https://aws.amazon.com/blogs/aws/now-available-version-1-0-of-the-aws-sdk-for-go/

**Comment by torarnv** [comment]
Prevents us from using eg. `minio` for testing the s3 stuff, as we don't support signature V4, only V2.

**Comment by harshavardhana** [comment]
> The aws/s3 dep is not maintained anymore, see mitchellh/goamz#255
> 
> We should use this instead
> 
> https://aws.amazon.com/blogs/aws/now-available-version-1-0-of-the-aws-sdk-for-go/

Or alternatively http://github.com/minio/minio-go can be used :-)

**Comment by torarnv** [comment]
See also https://github.com/concourse/s3-resource/commit/3fb5ed0da945b0071541b23fb778d2fab63637da
