### ISSUE TITLE
Add a source parameter to avoid dump "pre"

### ISSUE THREAD

**Issue by evanchaoli** [concourse/semver-resource#93]
Our users are heavily using `semver` resource to manage versions.

Recently some users raised requirement to me. They want to generate version like `1.0.0-SNAPSHOT`, but `semver` seems to not support that. If we use `pre`, generated version will be `1.0.0-SNAPSHOT.1`, and additional pre-version is appended.

After digging deeper, we found that the underlying `blang/semver` also support a `Build` field, but the problem is that `Build` is appended with a `+` sign, like `1.0.0+Build`, and the semver standard requires "+" before Build. So we don't want to break the standard.

But the standard doesn't require "pre" to have extra version appended. Thus we are thinking a solution to add a parameter "no-pre-version" to source of semver resource. If this flag is turned on, then just append `pre` to version without attaching an extra version.

If this solution is ok, we can raise a PR. @vito

**Comment by vito** [comment]
Sounds reasonable, but I think I'd put it in `params` instead of `source` since that's where `pre` is always set. :thinking: Does that matter for you use case?

**Comment by evanchaoli** [comment]
The reason why I proposed to put the flag in `source` instead of `params` is that, a `semver` resource may be `put` multiple times in a pipeline, so that putting the flag in `source` will avoid some duplicate code. Can we set in both `source` and `params`? `Params` will overwrite `source` if set in both places.

**Comment by vito** [comment]
fixed by #94
