### ISSUE TITLE
[Question] How to rebuild the latest build version?

### ISSUE THREAD

**Issue by mlikhachev** [concourse/semver-resource#95]
Hello.

We use Concourse with semver-resource to build the project.

This is how it is set up:

- get: git
- put: version
  params: {bump: patch}
- put: docker-image

The next question came up.

If a particular build failed, how do we rebuild a project with the same version?

Now I only thought of increasing the version in advance at the end of the build, but it looks clumsy.

Of course, we can remove put steps in the build manifest, but I think there should be a better solution.

Thank you in advance.

**Comment by tnwhitwell** [comment]
Possible suggestion: bump in the `get` job, and only `put` it when the build has passed?

**Comment by vito** [comment]
@tnwhitwell has it. That's what we do in our pipelines. We also tend to do version bumps in a tiny single-purpose job to minimize the chance of failure.
